"""empty message

Revision ID: 5bcac56f22cc
Revises: 4649bc1a9929
Create Date: 2019-03-27 15:25:45.874408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcac56f22cc'
down_revision = '4649bc1a9929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_permission', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_permission', 'parent_id')
    # ### end Alembic commands ###
